version: '3'

services:
   redis:
     image: docker.io/redis:6.2.6-alpine
     restart: always
     expose:
       - "6379"

   service2:
     depends_on:
       - redis
     image: service2:latest
     restart: always
     expose:
       - "19003"
     environment:
       GRPC_SERVER_PORT: "19003"
       REDIS_HOST: redis
       REDIS_PORT: "6379"

   service1:
     depends_on:
       - service2
     image: service1:latest
     ports:
       - "8000:8080"
     restart: always
     environment:
       API_PORT: "8080"
       GRPC_SERVER_HOST: service2
       GRPC_SERVER_PORT: "19003"
