---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: local
spec:
  storageClassName: sample
  capacity:
          storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv1
