kind: Service
apiVersion: v1
metadata:
  name: service1-service
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - name: http
      protocol: TCP
      port: 808
      targetPort: 8080
      nodePort: 30808
      protocol: TCP
      name: http
