---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: service1:latest
          ports:
          - containerPort: 8080
            name: service1
          volumeMounts:
            - name: service1-data
              mountPath: /var/www
          env:
            - name: API_PORT
              value: 8080
            - name: GRPC_SERVER_HOST
              value: service2-service.default.svc.cluster.local
            - name: GRPC_SERVER_PORT
              value: 19003
      volumes:
        - name: service1-data
          persistentVolumeClaim:
            claimName: service1-volume