---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  labels:
    type: local
spec:
  storageClassName: pv-redis
  capacity:
          storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-redis